module

public import Mathlib.Analysis.Normed.Module.WeakDual
public import Mathlib.Analysis.LocallyConvex.ContinuousOfBounded

public section

open Set Topology Metric LinearMap


variable {𝕜 E F : Type*} [NontriviallyNormedField 𝕜] [AddCommGroup E]
    [Module 𝕜 E] [AddCommGroup F] [Module 𝕜 F] (B : E →ₗ[𝕜] F →ₗ[𝕜] 𝕜) (U : Set E)

#check polar B U

variable (U : Set F) (B : E →ₗ[𝕜] F →ₗ[𝕜] 𝕜) --(U_nhds : U ∈ 𝓝 (0 : E))

def s := {p | ∃ f ∈ B.flip.polar U, p = Seminorm.comp (normSeminorm 𝕜 𝕜) (B f)}

lemma absorbing (v : F) : ∃ t : 𝕜, t ≠ 0 ∧ t • v ∈ U := by sorry

/- This should be generalized, and furthermore ought to already exist! -/
lemma pointwise_bound (v : F) : ∃ M, ∀ p ∈ s U B, p v ≤ M := by
  obtain ⟨t , htnz, ht⟩ := absorbing (𝕜 := 𝕜) U v
  use ‖t‖⁻¹
  have h : 0 < ‖t‖ := by aesop
  intro p hp
  obtain ⟨f, hfmem, hdef⟩ := hp
  rw [hdef]
  have A := LinearMap.polar_mem B (fun x ↦ ‖(B x) (t • v)‖ ≤ 1)
     (t • v) (fun x a ↦ a) f (hfmem (t • v) ht)
  grw [LinearMap.map_smul (B f) t v, norm_smul t ((B f) v)] at A
  have F : ‖t‖ * ‖t‖⁻¹ = 1 := by aesop
  exact (mul_le_mul_iff_of_pos_left h).mp <| le_of_le_of_eq A (id (Eq.symm F))

theorem correct_bddness : BddAbove ((↑)'' (s U B) : Set (F → ℝ)) := by
  choose g hg using pointwise_bound U B
  refine ⟨g, ?_⟩
  intro f hf
  rcases hf with ⟨p, hp, rfl⟩
  intro v
  exact hg v p hp

variable [TopologicalSpace E] [ContinuousSMul 𝕜 E]

/- It seems that `Seminorm 𝕜 F` is a SupSet, i.e. one can define
   `sSup s` for any `s : Set (Seminorm 𝕜 F)`. The `SupSet` instance
   gives a conditional, though, and so if there isn't a proof that the
   family of seminorms is pointwise bounded as functions, then `sSup s = ⊥`.
   So it seems the way to work with this is to supply `correct_bddness` above
   as an argument to `Seminorm.sSup_apply` to ensure that the right formula is used
   for the Mackey-Arens Seminorm. -/

/- Now to go and build the family of seminorms from polars of nhds of zero.
Need `WithSeminorms` which is the proposition that a topology is generated by
a system of seminorms. We then have `WithSeminorms.toLocallyConvexSpace` if we need it.
We can use `SeminormFamily` as an input to all of this, but this is an abbrev.
-/

noncomputable def MA_family : {U | U ∈ 𝓝 (0 : E)} → Seminorm 𝕜 E :=
  fun U ↦ sSup {p | ∃ f ∈ B.polar U, p = Seminorm.comp (normSeminorm 𝕜 𝕜) (B.flip f)}

/- We can now assert that the topology on V is generated by these seminorms coming from polars. -/
noncomputable def Assoc_Top := WithSeminorms (MA_family B)

/- We haven't actually built a topology here, but just are asserting that the topology on `V`
came from these seminorms. -/



end
