module

public import Mathlib.Analysis.Normed.Module.WeakDual
public import Mathlib.Analysis.LocallyConvex.ContinuousOfBounded

public section

variable {𝕜 V F : Type*} [NontriviallyNormedField 𝕜] [AddCommMonoid V] [Module 𝕜 V]
    [TopologicalSpace V] [AddCommMonoid F] [Module 𝕜 F]

class IsCompatible (b : F →ₗ[𝕜] V →ₗ[𝕜] 𝕜) : Prop where
  range_eq_range : b.range = (ContinuousLinearMap.coeLM 𝕜).range
  injective : Function.Injective b

lemma IsCompatible.continuous (b : F →ₗ[𝕜] V →ₗ[𝕜] 𝕜) [h : IsCompatible b]
    (x : F) : Continuous (b x) :=
  have ⟨y, hy⟩ := Submodule.ext_iff.mp h.range_eq_range (b x) |>.mp (b.mem_range_self x)
  hy ▸ y.continuous

noncomputable def IsCompatible.equiv (b : F →ₗ[𝕜] V →ₗ[𝕜] 𝕜) [h : IsCompatible b] :
    F ≃ₗ[𝕜] StrongDual 𝕜 V :=
  .ofBijective
    { toFun x := ⟨b x, h.continuous b x⟩,
      map_add' _ _ := by ext; simp,
      map_smul' _ _ := by ext; simp }
    ⟨fun _ _ ↦ by simp [h.injective.eq_iff], fun x ↦
      have ⟨y, hy⟩ := h.range_eq_range ▸ LinearMap.mem_range_self _ x
      ⟨y, ContinuousLinearMap.ext fun _ ↦ congr($hy _)⟩⟩
end

section

variable {𝕜 V F : Type*} [NontriviallyNormedField 𝕜] [AddCommMonoid V] [Module 𝕜 V]
    [TopologicalSpace V] [AddCommMonoid F] [Module 𝕜 F]

lemma IsCompatible.equiv_apply (b : F →ₗ[𝕜] V →ₗ[𝕜] 𝕜) [h : IsCompatible b]
    (x : F) : h.equiv b x = ⟨b x, h.continuous b x⟩ := rfl

@[simp] lemma IsCompatible.equiv_apply_apply (b : F →ₗ[𝕜] V →ₗ[𝕜] 𝕜) [h : IsCompatible b]
    (x : F) (y : V) : h.equiv b x y = b x y := rfl

end

public section

open Set Topology Metric LinearMap

/- There may be reasons to switch all of this to `WeakDual.polar`, but I don't know yet. -/

variable {𝕜 E F : Type*} [NontriviallyNormedField 𝕜] [AddCommGroup E]
    [Module 𝕜 E] [AddCommGroup F] [Module 𝕜 F] (B : E →ₗ[𝕜] F →ₗ[𝕜] 𝕜) (U : Set E)

variable {U : Set F} (B : E →ₗ[𝕜] F →ₗ[𝕜] 𝕜)

variable (U) in
def s := {p | ∃ f ∈ B.flip.polar U, p = Seminorm.comp (normSeminorm 𝕜 𝕜) (B f)}

variable [TopologicalSpace F] [ContinuousSMul 𝕜 F]

lemma Filter.nhd_zero_absorb (v : F) (hnhd : U ∈ 𝓝 (0 : F)) :
    ∀ᶠ t in 𝓝 (0 : 𝕜), ((fun t ↦ t • v) t) ∈ U :=
  ContinuousAt.eventually_mem
    (by continuity : Continuous (fun t : 𝕜 ↦ t • v)).continuousAt (by rwa [zero_smul])

lemma nhd_zero_nonemp_nontrivially_normed_field : ∀ U ∈ 𝓝 (0 : 𝕜), ∃ t ∈ U, t ≠ 0 := by
  intro U hU
  have := NormedField.exists_norm_lt (α := 𝕜)

/- This should be generalized, and furthermore ought to already exist! -/
lemma pointwise_bound (hnhd : U ∈ 𝓝 (0 : F)) (v : F) : ∃ M, ∀ p ∈ s U B, p v ≤ M := by
  have h_absorb : ∃ t : 𝕜, t ≠ 0 ∧ t • v ∈ U := by
    have A := Filter.nhd_zero_absorb (𝕜 := 𝕜) v hnhd
    simp only at A
    dsimp [Filter.Eventually] at A
    rw [Metric.mem_nhds_iff] at A
    obtain ⟨ε, hε, h⟩ := A
    obtain ⟨r, hr, hr1⟩ := NormedField.exists_norm_lt (α := 𝕜) hε
    use r
    constructor
    · exact norm_pos_iff.mp hr
    · exact mem_preimage.mp (h <| mem_ball_zero_iff.mpr hr1)
  obtain ⟨t , htnz, ht⟩ := h_absorb
  use ‖t‖⁻¹
  have h : 0 < ‖t‖ := by aesop
  intro p hp
  obtain ⟨f, hfmem, hdef⟩ := hp
  rw [hdef]
  have A := LinearMap.polar_mem B (fun x ↦ ‖(B x) (t • v)‖ ≤ 1)
     (t • v) (fun x a ↦ a) f (hfmem (t • v) ht)
  grw [LinearMap.map_smul (B f) t v, norm_smul t ((B f) v)] at A
  have F : ‖t‖ * ‖t‖⁻¹ = 1 := by aesop
  exact (mul_le_mul_iff_of_pos_left h).mp <| le_of_le_of_eq A (id (Eq.symm F))

theorem correct_bddness (hnhd : U ∈ 𝓝 (0 : F)) : BddAbove ((↑)'' (s U B) : Set (F → ℝ)) := by
  choose g hg using pointwise_bound B hnhd
  refine ⟨g, ?_⟩
  intro f hf
  rcases hf with ⟨p, hp, rfl⟩
  intro v
  exact hg v p hp

/- It seems that `Seminorm 𝕜 E` is a SupSet, i.e. one can define
   `sSup s` for any `s : Set (Seminorm 𝕜 E)`. The `SupSet` instance
   gives a conditional, though, and so if there isn't a proof that the
   family of seminorms is pointwise bounded as functions, then `sSup s = ⊥`.
   So it seems the way to work with this is to supply `correct_bddness` above
   as an argument to `Seminorm.sSup_apply` to ensure that the right formula is used
   for the Mackey-Arens Seminorm. -/

/- Now to go and build the family of seminorms from polars of nhds of zero.
Need `WithSeminorms` which is the proposition that a topology is generated by
a system of seminorms. We then have `WithSeminorms.toLocallyConvexSpace` if we need it.
We can use `SeminormFamily` as an input to all of this, but this is an abbrev.
-/

noncomputable def MA_family : {U | U ∈ 𝓝 (0 : F)} → Seminorm 𝕜 F :=
  fun U ↦ sSup {p | ∃ f ∈ B.flip.polar U, p = Seminorm.comp (normSeminorm 𝕜 𝕜) (B f)}

/- We can now assert that the topology on V is generated by these seminorms coming from polars. -/
noncomputable def Assoc_Top := WithSeminorms (MA_family B)

/- We haven't actually built a topology here, but just are asserting that the topology on `F`
came from these seminorms. -/

theorem bulk_of_Mackey_Arens : IsCompatible B ↔ WithSeminorms (MA_family B) := by
  constructor
  · intro h
    have h1 := h.1
    have h2 := h.2
    sorry
  · sorry

/- Once we get this in the right form, in the end we need to show that taking
suprema over arbitrary w*-compact subsets of functionals (to define the purported Mackey Top)
reduces via an equicontinuity argument using the compactness and absorption to considering
polars. -/

end
