import Mathlib.Topology.Algebra.NonUnitalStarAlgebra
import Mathlib.Topology.Algebra.StarSubalgebra
import Mathlib.Algebra.Algebra.Spectrum.Quasispectrum
import Mathlib.Data.Complex.Basic

/-! # Notation for C⋆-algebras

This file collects the notations avaiable in the `CStarAlgebra` namespace.

In Mathlib, we already have `A⁺¹ := Unitization ℂ A`.
-/

/-- The unital C⋆-subalgebra generated by a single element. -/
scoped[CStarAlgebra] notation "C⋆¹(" x ")" => StarAlgebra.elemental ℂ x

/-- The non-unital C⋆-subalgebra generated by a single element. -/
scoped[CStarAlgebra] notation "C⋆(" x ")" => NonUnitalStarAlgebra.elemental ℂ x

@[inherit_doc]
scoped[CStarAlgebra] notation "σ" => spectrum

@[inherit_doc]
scoped[CStarAlgebra] notation "σₙ" => quasispectrum
