import LeanOA.ForMathlib.Topology.Algebra.NonUnitalStarAlgebra
import Mathlib.Topology.Algebra.StarSubalgebra
import Mathlib.Analysis.CStarAlgebra.Classes
import Mathlib.Algebra.Algebra.Quasispectrum

/-! # Notation for C⋆-algebras

This file collects the notations avaiable in the `CStarAlgebra` namespace.

In Mathlib, we already have `A⁺¹ := Unitization ℂ A`.
-/

/-- The unital C⋆-subalgebra generated by a single element. -/
scoped[CStarAlgebra] notation "C⋆¹(" x ")" => StarAlgebra.elemental ℂ x

/-- The non-unital C⋆-subalgebra generated by a single element. -/
scoped[CStarAlgebra] notation "C⋆(" x ")" => NonUnitalStarAlgebra.elemental ℂ x

@[inherit_doc]
scoped[CStarAlgebra] notation "σ" => spectrum

@[inherit_doc]
scoped[CStarAlgebra] notation "σₙ" => quasispectrum


namespace CStarAlgebra

noncomputable instance unitalElemental {A : Type*} [CStarAlgebra A] (x : A) : CStarAlgebra C⋆¹(x) where

noncomputable instance nonUnitalElemental {A : Type*} [NonUnitalCStarAlgebra A] (x : A) : NonUnitalCStarAlgebra C⋆(x) where

end CStarAlgebra
