import Mathlib.Topology.Algebra.NonUnitalStarAlgebra
import Mathlib.Topology.Algebra.StarSubalgebra
import Mathlib.Analysis.CStarAlgebra.Classes
import Mathlib.Algebra.Algebra.Spectrum.Quasispectrum

/-! # Notation for C⋆-algebras

This file collects the notations avaiable in the `CStarAlgebra` namespace.

In Mathlib, we already have `A⁺¹ := Unitization ℂ A`.
-/

/-- The unital C⋆-subalgebra generated by a single element. -/
scoped[CStarAlgebra] notation "C⋆¹(" x ")" => StarAlgebra.elemental ℂ x

/-- The non-unital C⋆-subalgebra generated by a single element. -/
scoped[CStarAlgebra] notation "C⋆(" x ")" => NonUnitalStarAlgebra.elemental ℂ x

@[inherit_doc]
scoped[CStarAlgebra] notation "σ" => spectrum

@[inherit_doc]
scoped[CStarAlgebra] notation "σₙ" => quasispectrum


namespace CStarAlgebra

variable {A : Type*}

noncomputable instance [CStarAlgebra A] (x : A) :
    CStarAlgebra C⋆¹(x) where

noncomputable instance [NonUnitalCStarAlgebra A] (x : A) :
    NonUnitalCStarAlgebra C⋆(x) where

noncomputable instance [CStarAlgebra A] (x : A) [IsStarNormal x] :
    CommCStarAlgebra C⋆¹(x) where

noncomputable instance [NonUnitalCStarAlgebra A] (x : A) [IsStarNormal x] :
    NonUnitalCommCStarAlgebra C⋆(x) where

end CStarAlgebra
