import LeanOABlueprint.Base

open Verso.Genre
open Verso.Genre.Manual
open Informal

#doc (Manual) "Projection Lemmas" =>

Let $`\mathcal{A}` be a unital $`C^*`-algebra in this chapter. Here we collect relevant
results about (self-adjoint) projections in $`\mathcal{A}`. Recall that an element $`p` in a
$`C^*`-algebra is a projection if $`p^2 = p^* = p`. By the Spectral Mapping Theorem (or using
the full Gelfand Duality), a self-adjoint element $`a \in \mathcal{A}` is a projection if and
only if the spectrum of $`a` is contained in $`\{0, 1\}`.

:::lemma_ "lem:proj_le_one" (tags := "mathlib") (lean := "IsStarProjection.le_one") (uses := "lem:selfadjoint_le_norm")
For all projections $`p \in \mathcal{A}`, $`p \le 1`.
:::

:::proof "lem:proj_le_one"
We can get this by Gelfand duality (cf. Sakai 1.2.3) and
{bpref "lem:selfadjoint_le_norm"}[].
:::

:::lemma_ "lem:proj_sub_pos_iff_comm_eq_self" (lean := "IsStarProjection.le_tfae") (uses := "lem:star_conj_pos, lem:proj_le_one")
Let $`\mathcal{A}` be a $`C^*`-algebra and $`p, q \in \mathcal{A}` be projections. Then
$`p - q \ge 0` if and only if $`qp = pq = q`.
:::

:::proof "lem:proj_sub_pos_iff_comm_eq_self"
By {bpref "lem:star_conj_pos"}[], if $`p - q \ge 0` then
$`q(p - q)q = qpq - q^3 = qpq - q \ge 0`. By {bpref "lem:proj_le_one"}[], we have $`p \le 1`,
and employing {bpref "lem:star_conj_pos"}[] we obtain $`qpq \le q1q = q`. Since
$`qpq \ge q` and $`qpq \le q` we have $`qpq = q`, which implies that $`q(p - q)q = 0`. By the
$`C^*`-property of the norm, we have $`\|(p - q)^{1/2} q\|^2 = \|q(p - q)q\| = 0` and so
$`(p - q)^{1/2} q = 0` and therefore $`(p - q)q = (p - q)^{1/2}(p - q)^{1/2} q = 0`. It
follows that $`pq = q`, and taking adjoints, $`qp = q`. Conversely, if $`qp = pq = q`, one
easily checks that $`p - q` is a projection, and so its spectrum is contained in
$`\{0, 1\}` and it is positive.
:::

:::corollary "cor:proj_sub_of_subproj" (lean := "IsStarProjection.le_tfae") (uses := "lem:proj_sub_pos_iff_comm_eq_self")
For all projections $`p, q \in \mathcal{A}` such that $`q \le p`, $`p - q` is a projection.
:::

The next results are specific to $`W^*`-algebras.

:::proposition "prop:one_sided_ideals_in_wstar_proj_Sak_1_10_1" (uses := "lem:star_left_mul_right_mul_sig_cts_Sak_1_7_8, cor:sig_clos_of_cstar_is_wstar_Sak_1_7_9, lem:proj_sub_pos_iff_comm_eq_self, lem:wstar_unital")
(Sakai 1.10.1) Let $`\mathcal{L}` (resp. $`\mathcal{R}`) be a left (resp. right)
$`\sigma(M, M_*)`-closed ideal of a $`W^*`-algebra $`M`. Then there exists a unique
projection $`p` (resp. $`q`) in $`M` so that $`\mathcal{L} = Mp` (resp.
$`\mathcal{R} = qM`).
:::

:::proof "prop:one_sided_ideals_in_wstar_proj_Sak_1_10_1"
Suppose $`\mathcal{L}` is a $`\sigma`-closed left ideal. By
{bpref "lem:star_left_mul_right_mul_sig_cts_Sak_1_7_8"}[], $`\mathcal{L}^*` is also
$`\sigma`-closed and $`\mathcal{N} = \mathcal{L} \cap \mathcal{L}^*` is a $`\sigma`-closed
$`*`-subalgebra of $`M`, and therefore by
{bpref "cor:sig_clos_of_cstar_is_wstar_Sak_1_7_9"}[] is a $`W^*`-subalgebra of $`M`. Let
$`p` be the identity of $`\mathcal{N}`, which exists by {bpref "lem:wstar_unital"}[]. Since
$`\mathcal{L}` is a left ideal, $`xp \in \mathcal{L}` for any $`x \in M`, thus
$`Mp \subseteq \mathcal{L}`; conversely, $`xp = x` for any $`x \in \mathcal{L}`, since $`p`
is the identity of $`\mathcal{N}`, thus $`\mathcal{L} \subseteq Mp`.

If $`p_1` is another projection in $`M` such that $`\mathcal{L} = Mp_1` then $`Mp = Mp_1` and
$`p_1 = xp` for some $`x \in M`. By the self-adjointness of $`p_1` we have
$`p_1 = px^* xp` and therefore $`p_1 p = p p_1 = p_1`, and therefore $`p_1 \le p` by
{bpref "lem:proj_sub_pos_iff_comm_eq_self"}[]. We get $`p \le p_1` using the same argument.
The claim for right ideals follows mutatis mutandis.
:::

:::proposition "prop:proj_compl_lat_wstar_Sak_1_10_2" (uses := "prop:one_sided_ideals_in_wstar_proj_Sak_1_10_1, lem:proj_sub_pos_iff_comm_eq_self")
(Sakai 1.10.2) Let $`M` be a $`W^*`-algebra. Its set $`M^p` of projections is a complete
lattice with respect to $`\le`.
:::

:::proof "prop:proj_compl_lat_wstar_Sak_1_10_2"
Let $`\{e_i\}_{i \in \mathbb{I}}` be any set of projections in $`M`. Consider
$`\mathcal{L}_1`, the $`\sigma`-closed left ideal generated by
$`\{Me_i\}_{i \in \mathbb{I}}`, and $`\mathcal{L}_2 = \bigcap_{i \in \mathbb{I}} Me_i`. By
{bpref "prop:one_sided_ideals_in_wstar_proj_Sak_1_10_1"}[] there exist projections
$`e_1, e_2` in $`M` so that $`\mathcal{L}_1 = Me_1` and $`\mathcal{L}_2 = Me_2`. By
{bpref "lem:proj_sub_pos_iff_comm_eq_self"}[], we know $`e_i \le e_1` and $`e_2 \le e_i` for
any $`i \in \mathbb{I}`. (To prove the first of these, since $`e_i = xe_1` for some
$`x \in M`, we have by the self-adjointness of $`e_i` that $`e_i = e_1 x^* x e_1` and so
$`e_1 e_i = e_i e_1 = e_i` and so $`e_i \le e_1`. The other direction is analogous.)

Furthermore, if $`p \in M^p` is another projection that is an upper bound for all the $`e_i`
then $`Me_1 \subseteq Mp` since $`\mathcal{L}_1 = Me_1` is the left ideal generated by the
$`e_i`. It follows that $`e_1 \le p` by the same calculation we just did. If $`p \in M^p` is
a lower bound for all the $`e_i` then $`Mp \subseteq Me_i` for every $`i \in \mathbb{I}` and
so $`Mp \subseteq \bigcap_i Me_i = Me_2` and we obtain $`p \le e_2`. It follows that
$`e_1 = \sup(e_i)` and $`e_2 = \inf(e_i)`.
:::
