import LeanOABlueprint.Base

open Verso.Genre
open Verso.Genre.Manual
open Informal

#doc (Manual) "WStarAlgebras and their Topologies" =>

# Basic Definitions and Results

In this section we collect basic definitions and results about $`C^*`-algebras and
$`W^*`-algebras.

An associative algebra $`\mathcal{A}` over the complex numbers is called a *normed algebra*
if there is a map assigning to every $`x \in \mathcal{A}` a real number $`\|x\|`, and this
map satisfies:

1. $`\|x\| \ge 0` and $`\|x\| = 0 \iff x = 0`;
2. $`\|x + y\| \le \|x\| + \|y\|`;
3. $`\|\lambda x\| = |\lambda| \|x\|`;
4. $`\|xy\| \le \|x\| \|y\|`.

If $`\mathcal{A}` is also complete with respect to the norm, it is called a *Banach algebra*.
A mapping $`{}^* : \mathcal{A} \to \mathcal{A}` is called an *involution* if it satisfies:

1. $`(x^*)^* = x`;
2. $`(x + y)^* = x^* + y^*`;
3. $`(xy)^* = y^* x^*`;
4. $`(\lambda x)^* = \overline{\lambda} x^*`,

where $`\lambda` above is a complex number.

:::definition "def:cstar_def" (tags := "mathlib") (lean := "CStarAlgebra, NonUnitalCStarAlgebra")
A Banach algebra $`\mathcal{A}` with an involution is a $`C^*`-*algebra* if the relation
$`\|x^* x\| = \|x\|^2` holds for every $`x \in \mathcal{A}`. A $`C^*`-algebra is *unital* if
it has a multiplicative identity.
:::

:::lemma_ "lem:star_pres_norm_Sak_1_1_6" (tags := "mathlib") (lean := "CStarRing.to_normedStarGroup") (uses := "def:cstar_def")
(Sakai 1.1.6) The involution on a $`C^*`-algebra preserves the norm.
:::

:::proof "lem:star_pres_norm_Sak_1_1_6"
Note $`\|x\|^2 = \|x^* x\| \le \|x^*\| \|x\|`, and
$`\|x^*\|^2 \le \|x x^*\| \le \|x\| \|x^*\|`.
:::

:::theorem "thm:comm_cstar_cts_fcns_Sak_1_2_1" (tags := "mathlib") (lean := "gelfandStarTransform") (uses := "def:cstar_def")
(Sakai 1.2.1) Every commutative, unital $`C^*`-algebra $`\mathcal{A}` is
$`*`-isomorphic to $`C(K)`, the algebra of complex-valued continuous functions on $`K`,
where $`K` is the compact Hausdorff space of maximal ideals of $`\mathcal{A}`. (Note $`C(K)`
is itself a $`C^*`-algebra with pointwise complex conjugation as $`*` and the uniform norm.)
:::

:::proof "thm:comm_cstar_cts_fcns_Sak_1_2_1"
By Banach algebra theory, the Gelfand transform provides a homomorphism of $`\mathcal{A}`
into $`C(K)`. A standard calculation using the $`C^*`-identity shows that it is isometric.
Mapping a self-adjoint element $`h` to the unit circle (complex exponentiation) one can show
that the spectrum lands on the unit circle and so the spectrum of $`h` is in the reals. The
spectrum of an element in $`C(K)` is its range, from which $`*`-preservation follows.
:::

:::corollary "cor:nonunital_gelfand_Sak_1_2_2" (uses := "thm:comm_cstar_cts_fcns_Sak_1_2_1")
(Sakai 1.2.2) Let $`\mathcal{A}` be a commutative $`C^*`-algebra without identity. Then
$`\mathcal{A}` is $`*`-isomorphic to the algebra $`C_0(\Omega)` of continuous functions
vanishing at infinity on a locally compact Hausdorff space $`\Omega`. The space $`\Omega` is
called the *spectrum space* of $`\mathcal{A}`.
:::

:::corollary "cor:spec_sa_homeo_spec_cstar" (tags := "mathlib") (lean := "cfcₙ, IsSelfAdjoint.instNonUnitalIsometricContinuousFunctionalCalculus") (uses := "cor:nonunital_gelfand_Sak_1_2_2")
Let $`\mathcal{A}` be a commutative $`C^*`-algebra generated by a single self-adjoint element
$`a` and let $`\Omega` be the spectrum space of $`\mathcal{A}`. Then
$`\Omega \cup \{\infty\}` is homeomorphic to $`\sigma(a) \cup \{0\}` and
$`\mathcal{A} = C_0(\sigma(a) \cup \{0\})`, the algebra of complex-valued continuous
functions on $`a`'s spectrum that vanish at $`0`.
:::

:::proof "cor:spec_sa_homeo_spec_cstar"
Consider the function $`\xi` sending a point $`t \in \Omega` to $`a(t) \in \sigma(a)` and
$`\infty` to $`0`, where $`a(\cdot)` is the image of $`a` under the Gelfand transform. Since
$`\mathcal{A}` is generated by $`a`, the map is bijective. The map is continuous, since $`a`
is a continuous function. We have a continuous bijection from a compact space (the one-point
compactification of $`\Omega`) into a Hausdorff space $`\sigma(a) \cup \{0\}`, and by
{bpref "lem:homeo_of_cts_bij_cpt_haus"}[] this is a homeomorphism.
:::

:::lemma_ "lem:one_is_extreme" (lean := "CStarAlgebra.one_mem_extremePoints_unitClosedBall") (uses := "thm:comm_cstar_cts_fcns_Sak_1_2_1, lem:star_pres_norm_Sak_1_1_6")
In a unital $`C^*`-algebra $`\mathcal{A}`, the identity $`1` is an extreme point of the
closed unit sphere $`S`.
:::

:::proof "lem:one_is_extreme"
Suppose $`a, b \in S` and $`1 = \frac{a + b}{2}`. Then, since $`1 = 1^*`, we have
$`1 = \frac{a^* + b^*}{2}` and one checks that $`1 = \frac{c + d}{2}`, where
$`c = \frac{a + a^*}{2}` and $`d = \frac{b + b^*}{2}`. Now $`d = 2 - c` and so $`d` and $`c`
commute and each are self-adjoint (hence normal), and therefore $`C^*\{1, d, c\}` is
commutative and can be identified with $`C(K)` for a compact Hausdorff space $`K`. The
self-adjointness of $`c` and $`d`, the triangle inequality and
{bpref "lem:star_pres_norm_Sak_1_1_6"}[] imply that the ranges of the associated functions
$`f, g` are in $`[-1, 1]`. In order for $`f(t) + g(t) = 2` for all $`t \in K` it must be that
$`f(t)` and $`g(t)` are always $`1`, and thus $`c = d = 1`. Now $`2 = 2c = a + a^*` and so
$`a = 2 - a^*`, hence $`a` is normal and so the unital $`C^*`-subalgebra generated by $`a` is
commutative. Again represent the unital $`C^*`-algebra as $`C(K)` for some compact Hausdorff
$`K`. Let $`f` be the function corresponding to $`a`. We have $`\Re(f)(t) = 1` for all $`t`,
and hence $`\Re(f)(t)^2 = |f(t)| = 1` for all $`t` and $`\Im(f)(t) = 0` for all $`t`, and
therefore $`a = 1`.
:::

:::lemma_ "lem:fake_approx_unit" (uses := "cor:nonunital_gelfand_Sak_1_2_2")
Let $`x` be an extreme point of the norm unit ball of a $`C^*`-algebra $`\mathcal{A}`, so
that the $`C^*`-subalgebra generated by $`x^* x` is identified with $`C_0(\Omega)` as in
{bpref "cor:nonunital_gelfand_Sak_1_2_2"}[]. There exists a sequence $`(y_n)` of positive
elements in $`C_0(\Omega)` with $`\|y_n\| \le 1` for all $`n`, such that
$`\|(x^* x) y_n - x^* x\| \to 0` and $`\|(x^* x) y_n^2 - x^* x\| \to 0` as $`n \to \infty`.
:::

:::lemma_ "lem:extreme_partial_isom" (lean := "isStarProjection_star_mul_self_of_mem_extremePoints_unitClosedBall")
If $`x` is an extreme point of the norm unit ball of a $`C^*`-algebra $`\mathcal{A}`, then
$`x^* x` is a projection. That is, $`x` is a partial isometry.
:::

:::theorem "thm:cstar_unital_iff_extreme_Sak_1_6_1" (lean := "CStarAlgebra.isUnital_iff") (uses := "lem:one_is_extreme, lem:extreme_partial_isom")
(Sakai 1.6.1) A $`C^*`-algebra is unital if and only if its closed unit ball has an extreme
point.
:::

:::proposition "prop:extr_pos_projs_Sak_1_6_2" (lean := "isStarProjection_iff_mem_extremePoints_setOf_nonneg_inter_unitClosedBall")
(Sakai 1.6.2) Let $`P` be the set of positive elements in a $`C^*`-algebra $`\mathcal{A}`
with unit sphere $`S`. Then the extreme points of $`P \cap S` are the projections of
$`\mathcal{A}`.
:::

:::proposition "prop:extr_sa_sa_unitaries_Sak_1_6_3" (lean := "mem_extremePoints_isSelfAdjoint_and_mem_unitClosedBall_iff_isSelfAdjoint_and_mem_unitary") (uses := "prop:extr_pos_projs_Sak_1_6_2")
(Sakai 1.6.3) Let $`\mathcal{A}^s` be the set of self-adjoint elements in a $`C^*`-algebra
$`\mathcal{A}` with unit sphere $`S`. Then the set of extreme points of
$`\mathcal{A}^s \cap S` is the set of all self-adjoint unitary elements of $`\mathcal{A}`.
:::

:::definition "def:wstar_def" (lean := "Predual") (uses := "def:cstar_def")
A $`C^*`-algebra $`M` is called a $`W^*`-*algebra* if it is a dual Banach space, i.e. if
there exists a Banach space $`M_*` so that $`(M_*)^*` is isometrically isomorphic to $`M`.
We call $`M_*` a *predual* of $`M`.
:::

It is premature to fix a notation like $`M_*` in the above, but the aim of this project is to
prove that any two preduals of $`M` are isomorphic as Banach spaces, so we take the liberty
with Sakai of fixing a reference predual at the outset.

:::lemma_ "lem:sigma_closed_star_subalg_wstar" (uses := "def:wstar_def, def:sigma_top")
(Sakai 1.1.4) A self-adjoint, $`\sigma`-closed $`*`-subalgebra $`N` of a $`W^*`-algebra $`M`
is also a $`W^*`-algebra, since $`(M_* / N^0)^* = N`, where $`N^0` is the polar
(annihilator) of $`N` in $`M_*`, i.e. the set of $`\varphi \in M_*` such that
$`\varphi(x) = 0` for all $`x \in N`.
:::

# The Ultraweak (Sigma) Topology

:::definition "def:sigma_top" (lean := "Ultraweak") (uses := "def:wstar_def")
The weak-$`*` topology $`\sigma(M, M_*)` on a $`W^*`-algebra $`M` is called the
$`\sigma`-*topology*.
:::

:::lemma_ "lem:wstar_unital" (uses := "thm:cstar_unital_iff_extreme_Sak_1_6_1")
Every $`W^*`-algebra is unital.
:::

:::proof "lem:wstar_unital"
The norm unit ball of $`M = (M_*)^*` is closed in the $`\sigma`-topology, is convex, and so
has an extreme point by the Krein-Milman Theorem. By
{bpref "thm:cstar_unital_iff_extreme_Sak_1_6_1"}[], the result follows.
:::

:::lemma_ "lem:cut_down_sigma_closed_cts" (uses := "def:sigma_top")
(Sakai 1.7.6) Let $`p` be any projection in $`M`. Then the subalgebra $`pMp` is
$`\sigma`-closed and the mapping $`x \mapsto pxp` is $`\sigma`-continuous.
:::

:::lemma_ "lem:cut_down_of_wstar" (uses := "def:sigma_top, lem:cut_down_sigma_closed_cts, lem:sigma_closed_star_subalg_wstar")
If $`p \in M` is a projection, then $`pMp` is also a $`W^*`-algebra with identity $`p`.
:::

:::proof "lem:cut_down_of_wstar"
It is clear that $`eMe` is an algebra, since any sum or product of elements preserves the
pre- and post-multiplication by $`e`. It is also clear that $`e` is the multiplicative
identity of this algebra. The product-reversing property of $`*` and the fact that $`e` is a
self-adjoint projection imply that $`eMe` is a $`*`-algebra. By
{bpref "lem:sigma_closed_star_subalg_wstar"}[], if this $`*`-subalgebra is $`\sigma`-closed,
then it is a $`W^*`-subalgebra of $`M`. But this is the result of
{bpref "lem:cut_down_sigma_closed_cts"}[].
:::

:::lemma_ "lem:left_mul_proj_right_mul_proj_sig_cts_Sak_1_7_7" (uses := "def:sigma_top")
(Sakai 1.7.7) If $`p` is any projection of $`M`, then the mappings $`x \mapsto px` and
$`x \mapsto xp` are $`\sigma`-continuous.
:::

:::lemma_ "lem:star_left_mul_right_mul_sig_cts_Sak_1_7_8" (uses := "def:sigma_top")
(Sakai 1.7.8) The mappings $`x \mapsto x^*`, $`x \mapsto ax`, and $`x \mapsto xa` are
$`\sigma`-continuous for $`x, a \in M`.
:::

:::corollary "cor:sig_clos_of_cstar_is_wstar_Sak_1_7_9" (uses := "lem:left_mul_proj_right_mul_proj_sig_cts_Sak_1_7_7, lem:star_left_mul_right_mul_sig_cts_Sak_1_7_8, def:sigma_top")
(Sakai 1.7.9) Let $`H` be a subset of $`M` and $`\mathcal{A}` be the $`C^*`-subalgebra of
$`M` generated by $`H`, and let $`\overline{\mathcal{A}}` be the $`\sigma(M, M_*)`-closure of
$`\mathcal{A}`. Then $`\overline{\mathcal{A}}` is a $`W^*`-subalgebra of $`M`;  it is called
the $`W^*`-subalgebra of $`M` generated by $`H`. Moreover, $`\overline{\mathcal{A}}` is
commutative if $`\mathcal{A}` is commutative.
:::

:::lemma_ "lem:wstar_of_masa" (uses := "cor:sig_clos_of_cstar_is_wstar_Sak_1_7_9")
A maximal abelian $`*`-subalgebra $`\mathcal{A}` of a $`W^*`-algebra $`M` is also a
$`W^*`-algebra.
:::

:::proof "lem:wstar_of_masa"
By maximality, $`\mathcal{A} = \overline{\mathcal{A}}`, and so
{bpref "cor:sig_clos_of_cstar_is_wstar_Sak_1_7_9"}[] implies $`\mathcal{A}` is a
$`W^*`-subalgebra of $`M`.
:::

# Other Topologies on WStarAlgebras

In this section, let $`M` be a $`W^*`-algebra.

:::proposition "prop:loc_cvx_result"
The set of $`\sigma(M, M_*)`-continuous linear functionals is precisely $`M_*`.
:::

:::proof "prop:loc_cvx_result"
A standard result in the theory of locally convex topological vector spaces.
:::

:::definition "def:Mackey_top"
The locally convex topology on $`M` generated by the seminorms
$`p_K(x) = \sup_{\varphi \in K} |\varphi(x)|`, ranging over the $`\sigma(M_*, M)`-compact
subsets $`K` of $`M_*`, is called the *Mackey topology* on $`M`. We denote this topology by
$`\tau(M, M_*)`.
:::

The Mackey topology is the strongest topology on $`M` for which the functionals in $`M_*` are
all continuous.

:::definition "def:strong_top"
The locally convex topology on $`M` generated by the seminorms
$`x \mapsto \varphi(x^* x)^{1/2}` ranging over $`\varphi \in M_*` is called the *strong
topology*, or $`s`-*topology*, on $`M`. We denote it by $`s(M, M_*)`.
:::

The following result additionally uses the Mackey-Arens Theorem, so we may need to prove that
as well. By $`A \le B` on topologies below, we mean that $`A` is weaker than $`B`.

:::theorem "thm:sigma_le_s_le_tau" (uses := "def:Mackey_top, def:strong_top, def:sigma_top, prop:extr_sa_sa_unitaries_Sak_1_6_3")
We have $`\sigma(M, M_*) \le s(M, M_*) \le \tau(M, M_*)`.
:::

:::corollary "cor:sigma_eq_s_on_ball" (uses := "thm:sigma_le_s_le_tau")
The $`\sigma`-topology is equivalent to the $`s`-topology on the unit ball of $`M`, and hence
on bounded sets.
:::
